defmodule LiveLoad.Browser.Context do
  @moduledoc """
  The `LiveLoad.Browser.Context` is an isolated context where all operations of a `LiveLoad.Scenario` take places.
  It has a parent `LiveLoad.Browser`, and whatever private data is related to the current connection's underlying context.

  A context is generated by the `new_context/1` callback in the `LiveLoad.Browser.Connection` behaviour.
  Contexts must be isolated in terms of session - each user process in the load test gets its own `LiveLoad.Browser.Context`,
  and all of that user's operations will run on this context.

  Contexts may reuse browser processes, but their session data must be private. As an example, Playwright exposes contexts
  in order to optimize, however, alternate implementations like [LightPanda](https://lightpanda.io/) or [WebDriver](https://www.w3.org/TR/webdriver1/)
  do not have an equivalent (as of the time of writing). So if one were to write a WebDriver based `LiveLoad.Browser.Connection` implementation,
  they would have to ensure that each `LiveLoad.Browser.Context` is mapped to a full isolated WebDriver browser instance.
  """

  alias __MODULE__

  @type t() :: %__MODULE__{
          browser: LiveLoad.Browser.t(),
          private: %{optional(atom()) => term()}
        }

  defstruct [:browser, private: %{}]

  def new(%LiveLoad.Browser{} = browser) do
    %Context{browser: browser}
  end

  @spec put_private(context :: t(), key :: atom(), value :: term()) :: t
  def put_private(%Context{private: private} = context, key, value) when is_atom(key) do
    %{context | private: Map.put(private, key, value)}
  end
end
